services:
  - type: web
    name: luciddrop-backend
    runtime: node
    plan: free
    region: ohio
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: SOLANA_RPC
        sync: false
      - key: CASINO_PRIVATE_KEY
        sync: false
      - key: CASINO_WALLET_PUBLIC_KEY
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: NODE_ENV
        value: production
    healthCheckPath: /api/health
    autoDeploy: true
